### ISSUE TITLE
Merging with DupAlgorithm=Identical does not merge identical objects if there are are also samevalue duplicates

### ISSUE THREAD

**Issue by necebeci** [PaloAltoNetworks/pan-os-php#585]
## Describe the bug

Noticed a behaviour while using dupalgorithm=identical to merge address objects overriden at child DGs but with same value
In a DG hierarchy like below
-Global
--Region
---Country

Objects object-a, object-b and object-c all resolve to same value

- Global={object-a}
-- Region={object-b}
---Country={object-b(overriden with same value), object-c}

If we run the address-merger util with options below
`pan-os-php type=address-merger in=config.xml actions=display DupAlgorithm=identical allowmergingwithupperlevel location=Country outputformatset=country.set
 `
it doesn't merge object-b with parent, even though they resolve to same name&value pair

## Expected behavior

Same name&value identical pairs should be merged

## Current behavior

It's taking the samevalue objects into account and skips the merge operation

## Steps to reproduce

Shared config and steps privately

## Your Environment

root@3ddd6ed470e2:/share# pan-os-php version
 - PAN-OS-PHP version: 2.0.43 [UNIX]
 - /tools/pan-os-php/utils
 - PHP version: 7.4.3

**Comment by swaschkut** [comment]
-shared
--parent
---child

the problem here is the script per default pick the best match object from upper level:

- {object-a}

by using DupAlgorithm=identical {object-a} is NOT identical to {object-b}.

if you review your log output:
```
 - value 'ip-netmask-1.1.1.1'
   * using object from upper level : '/PanoramaConf:/AddressStore/Address:objA'
    - SKIP: object name '/child/AddressStore/Address:objC' [with value '1.1.1.1'] is not IDENTICAL
    - SKIP: object name '/parent/AddressStore/Address:objB' [with value '1.1.1.1'] is not IDENTICAL to object name from upperlevel '/PanoramaConf:/AddressStore/Address:objA' [with value '1.1.1.1'] 
```

- you will that the script is skipping parent:objB because of a different name.
- child:objB is here not print, because with 'allowmergingwithupperlevel' it is already chosen the parent:objB as these are identical.

nevertheless, I found another bug, which will be fixed and published soon.
with this bugfix you can use argument 'pickfilter=(name eq objB)'

so that the script is picking a different object by Name and replacing it.

With the version 2.0.50 - planned to be released next week the following is working:

`pan-os-php type=address-merger DupAlgorithm=identical allowmergingwithupperlevel location=child out=identical_merged.xml exportcsv=merger.html in=identical.xml 'pickfilter=(name eq objB)'
`

Please validate and reopen if needed.

**Comment by swaschkut** [comment]
please check version 2.0.50

introduced with #620
